# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3609e237ec8f1d5f3e42fefe532592775d58407d955ce4690f2734ca163b2088fcc263bf48dd6d539d378bd12eb40fa128ff0e7e2e1e06d0c330468e533c5cad

test:
  secret_key_base: a473ae5d6126ee0986986e2ffa75c19707e8d4c895d38dd71a61bb8bfbdd1cbc6637648f05957b3566d7ee26d1b826a2a48ef9b00cf11eeee3ffae5c56e9ab32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
